### PR TITLE
adjust logic for is_distributed

### PR DESCRIPTION
**Pull request by natechols**
@mpkocher I think this is half of what you had in mind, at least.  I have a complementary pbsmrtpipe change that appears to have the desired effect in combination with this.

### CODE REVIEW

**Comment by mpkocher** [comment]
Can you make is_distributable a positional arg, so it's explicit?

**Comment by mpkocher** [comment]
For completeness, would you also mind updating PbTestApp?

**Comment by natechols** [comment]
What do you want me to change in PbTestApp?

**Comment by mpkocher** [comment]
Fundamentally, all the values passed to the resolver and corresponding resolved values need to be represented as class vars to PbTestApp to the test assertions can be fully tested.

Currently, MAX_NPROC, TASK_OPTIONS are passed to the resolver, you would need to add IS_DISTRIBUTED. Similarly, the resolved value, RESOLVED_IS_DISTRIBUTED, would need to be added and a test assertion would need to be made. 

Does that make sense?

**Comment by natechols** [comment]
Okay, I get it now.  I think I managed to cover the main use cases here.

**Pull request merged**
