### PR TITLE
Add pacbio-manifest.json

### PR DESCRIPTION
**Pull request by mpkocher**

### CODE REVIEW

**Comment by mpkocher** [comment]
@natechols Does this make sense? If we consistently add these to the repos, then Herb can load these and concat them during the build process to create the "versions.json" in `/smrtlink-{SYSTEM-ID}/smrtsuite/current/etc`?

**Comment by natechols** [comment]
I don't understand why we would store the SHA here - or is the idea that Herb's build script would inject it?

**Comment by mpkocher** [comment]
I believe that we want to have access to the SHA from within the python code, so it would make sense to write the SHA to **init**.py (or something similar, not sure what the python best practices are). If we start writing the short SHA version format, then it would make sense to update this JSON file with this X.Y.Z-{GH-Short-SHA1} format, e.g., 0.1.3-ce635e6. (This is what the services are doing now)

Ideally, Herb shouldn't be doing any processing of the version string in the pacbio-manifest.json.

**Comment by mpkocher** [comment]
This isn't quite right, but I would like to get a repo or two into the build that have the pacbio-manifest.json.

**Pull request merged**
