### PR TITLE
handle verbosity arguments in resolved tool contract mode

### PR DESCRIPTION
**Pull request by natechols**
@mpkocher I'm pretty sure this does what we (and @pb-cdunn) want, it's a little more invasive though.  Basically I threw out the custom argv parsing in favor of a temporary argparser that respects verbosity arguments, and if none were used it falls back on the log level in the RTC (`INFO` by default)

### CODE REVIEW

**Comment by mpkocher** [comment]
This looks reasonable.

Do you see any way of accomplishing the same thing using an argparse action?  Perhaps using the closure trick from the subcomponents?

https://github.com/PacificBiosciences/pbcommand/blob/master/pbcommand/common_options.py#L105

**Comment by mpkocher** [comment]
The EMIT_TOOL_CONTRACT_OPTION  code path has a similar problem that is parsing the raw argv. Both of these cases might be better solved by an argparse action. This would require mutating the parser at pbparser_runner or pacbio_args_or_contract_runner.

**Comment by natechols** [comment]
It's not immediately obvious to me how to implement this, but I'll try tomorrow.

**Comment by mpkocher** [comment]
Let's just call this resolved fixed for now and maybe revisit this in the future.

I think your improvements are solving the current problem by accessing all the parsed args and propagating them correctly. Thanks for sorting this out.

**Pull request merged**
